export enum CvDataAction {
  SET_PROJECTS = "SET_PROJECTS",
  SET_CONTACTS = "SET_CONTACTS",
  SET_MENU = "SET_MENU",
  SET_BANNER = "SET_BANNER",
  SET_TECH_TITLE = "SET_TECH_TITLE",
  SET_PROJECTS_Y = "SET_PROJECTS_Y",
  SET_TECH_Y = "SET_TECH_Y",
  SET_CONTACT_Y = "SET_CONTACT_Y",
  SET_LANGUAGE = "SET_LANGUAGE",
}